// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7PatI5lagnKOloy37v8y9_8eV99dZkyY',
    appId: '1:212756282143:web:4ac27280faf125216fce2a',
    messagingSenderId: '212756282143',
    projectId: 'portfolio-f9007',
    authDomain: 'portfolio-f9007.firebaseapp.com',
    databaseURL: 'https://portfolio-f9007-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'portfolio-f9007.appspot.com',
    measurementId: 'G-8EFXWHPP08',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASlSK5SOXyZ2Yz0u2e94KxloQaMGwE6PE',
    appId: '1:212756282143:android:36fed323f4bc29326fce2a',
    messagingSenderId: '212756282143',
    projectId: 'portfolio-f9007',
    databaseURL: 'https://portfolio-f9007-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'portfolio-f9007.appspot.com',
  );

}